apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: us-east-1

nodeGroups:
  - name: worker-nodes
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 0
    maxSize: 2