apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: quarkus-hello-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
      namespace: quarkus-hello-demo
  template:
    metadata:
      labels:
        app: hello-app
        namespace: quarkus-hello-demo
    spec:
      containers:
        - name: hello-app
          image: wesleyfuchter/hello-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /health/live
            initialDelaySeconds: 1
            periodSeconds: 3
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 3
            timeoutSeconds: 2