apiVersion: v1
kind: Service
metadata:
  name: balance-service
  namespace: quarkus-cqrs-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: balance-app
    namespace: quarkus-cqrs-demo